# Generated by Django 3.2.8 on 2021-10-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustom',
            name='first_name',
            field=models.CharField(error_messages={'null': 'Not null'}, max_length=100, verbose_name='Primeiro nome'),
        ),
        migrations.AlterField(
            model_name='usercustom',
            name='last_name',
            field=models.CharField(error_messages={'null': 'Not null'}, max_length=100, verbose_name='Ultimo nome'),
        ),
    ]
