# Generated by Django 3.2.7 on 2021-10-09 01:56

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, verbose_name='Nome')),
                ('email', models.EmailField(error_messages={'unique': 'Este e-mail já está registrado.'}, max_length=254, unique=True)),
                ('birth_date', models.DateField(null=True, verbose_name='Data de Nascimento')),
                ('district', models.CharField(max_length=150, null=True, verbose_name='Bairro')),
                ('state', models.CharField(choices=[('default', 'Selecione um estado'), ('AC', 'Acre'), ('AL', 'Alagoas'), ('AM', 'Amazonas'), ('AP', 'Amapá'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MG', 'Minas Gerais'), ('MS', 'Mato Grosso do Sul'), ('MT', 'Mato Grosso'), ('PA', 'Pará'), ('PB', 'Paraiba'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('PR', 'Paraná'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('RS', 'Rio Grande do Sul'), ('SC', 'Santa Catarina'), ('SE', 'Sergipe'), ('SP', 'São Paulo'), ('TO', 'Tocantins')], default='default', max_length=25, verbose_name='Estados')),
                ('cpf_or_cnpj', models.CharField(choices=[('cpf', 'CPF'), ('cnpj', 'CNPJ')], default='cpf', max_length=10, verbose_name='CPF/CNPJ')),
                ('cpf_cnpj', models.CharField(error_messages={'unique': 'Este CPF/CNPF já está registrado.'}, max_length=18, unique=True, verbose_name='CPF/CNPJ')),
                ('address', models.CharField(max_length=250, null=True, verbose_name='Endereço')),
                ('photo', models.ImageField(blank=True, default='default.png', null=True, upload_to='images/upload', verbose_name='Imagem')),
                ('rg', models.CharField(error_messages={'unique': 'Este RG já está registrado.'}, max_length=15, unique=True, verbose_name='RG')),
                ('cep', models.CharField(max_length=15, null=True, verbose_name='CEP')),
                ('cell_phone', models.CharField(max_length=15, null=True, verbose_name='CEL')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Fone')),
                ('city', models.CharField(max_length=80, null=True, verbose_name='Cidade')),
                ('update_by', models.CharField(blank=True, max_length=30, null=True, verbose_name='Atualizado pelo usuário')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Criação')),
                ('update_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Data de atualização')),
                ('created_by_user', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'tbl_clients',
                'ordering': ['id'],
            },
        ),
    ]
