# Generated by Django 3.2.7 on 2021-10-09 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_clientmodel_created_by_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='created_by_user',
            field=models.CharField(default=None, max_length=150, verbose_name='Criado por'),
        ),
    ]
