# Generated by Django 3.2.7 on 2021-10-09 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0003_alter_clientmodel_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='cpf_cnpj',
            field=models.CharField(blank=True, max_length=18, verbose_name='CPF/CNPJ'),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, default='empty', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
