# Generated by Django 3.2.7 on 2021-10-09 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_auto_20211008_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='created_by_user',
            field=models.CharField(blank=True, default=1, max_length=30, verbose_name='Criado por'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='update_by',
            field=models.CharField(blank=True, default=1, max_length=30, verbose_name='Atualizado pelo usuário'),
            preserve_default=False,
        ),
    ]
