# Generated by Django 3.2.8 on 2021-10-13 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_auto_20211013_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmodel',
            name='complement',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Complemento'),
        ),
    ]
