# Generated by Django 3.2.7 on 2021-10-09 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_auto_20211008_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='cell_phone',
            field=models.CharField(max_length=15, null=True, verbose_name='CEL'),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='cpf_cnpj',
            field=models.CharField(blank=True, max_length=18, verbose_name='CPF/CNPJ'),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='rg',
            field=models.CharField(max_length=15, null=True, verbose_name='RG'),
        ),
    ]
