# Generated by Django 3.2.8 on 2021-10-13 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0006_clientmodel_complement"),
    ]

    operations = [
        migrations.RenameField(
            model_name="clientmodel",
            old_name="complement",
            new_name="complement_address",
        ),
        migrations.AddField(
            model_name="clientmodel",
            name="number_address",
            field=models.CharField(default=1, max_length=10, verbose_name="Número"),
            preserve_default=False,
        ),
    ]
