# Generated by Django 3.2.7 on 2021-10-09 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_auto_20211008_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='email',
            field=models.EmailField(blank=True, default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
