# Generated by Django 3.2.7 on 2021-10-09 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_alter_clientmodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
