# Generated by Django 3.2.7 on 2021-10-09 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_alter_clientmodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
