# Generated by Django 3.2.7 on 2021-10-09 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_auto_20211008_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='cpf_cnpj',
            field=models.CharField(error_messages={'unique': 'Este CPF/CNPF já está registrado.'}, max_length=18, unique=True, verbose_name='CPF/CNPJ'),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='rg',
            field=models.CharField(error_messages={'unique': 'Este RG já está registrado.'}, max_length=15, unique=True, verbose_name='RG'),
        ),
    ]
