# Generated by Django 3.2.7 on 2021-10-09 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0015_auto_20211008_2151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientmodel',
            old_name='created_by',
            new_name='created_by_user',
        ),
    ]
